### PR TITLE
[WIP] Update vocabulary to transition cop to watcher

### PR DESCRIPTION
**Pull request by mffiedler**
Update the term "cop" to be "watcher".   Simple straight substitution.

### CODE REVIEW

**Comment by mffiedler** [comment]
@paigerube14 @chaitanyaenr I need to test this with slack, but let me know what you think of the approach.

**Comment by chaitanyaenr** [comment]
@mffiedler approach looks good to me.

**Comment by paigerube14** [comment]
agreed! approach looks good

**Comment by mffiedler** [comment]
I got tangled in a branch/merge loop.  Closing this for cleaner PR

**Pull request closed without merging**
