### PR TITLE
Add Cerberus logo

### PR DESCRIPTION
**Pull request by chaitanyaenr**
Credits: Thanks to Mary Shakshober ( https://github.com/maryshak1996 )
for designing the logo.

Fixes https://github.com/openshift-scale/cerberus/issues/15

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
cc: @maryshak1996

**Comment by mffiedler** [comment]
@chaitanyaenr Should we commit the other image formats in a side directory?  or do you prefer to keep them outside of the repo?

**Comment by chaitanyaenr** [comment]
@mffiedler Added other image formats in the media directory. PTAL.

**Comment by mffiedler** [comment]
We probably only need full color, but no harm in keeping the others for now - the whole collection is only 800KB.   Merging.

**Pull request merged**
