### PR TITLE
Added support to ensure functionality isn't affected on new commit

### LINKED ISSUE #25: Test to check the functionality
We need tests in CI to make sure a new commit is not breaking the functionality of cerberus. We can just run the tool with iterations set to 3 and sleep time between each iteration set to 30 seconds instead of daemon mode to see if it's working as expected.

### PR DESCRIPTION
**Pull request by yashashreesuresh**
Fixes #25 

This commit:
- Ensures functionality of cerberus is not affected/broken by a
  new commit.
- Adds a functional test to ensure non-daemon mode of cerberus is
  not affected by a new commit.
- Adds a functional test to ensure the functionality of cerberus
  to collect detailed logs, events and metrics of failed components
  is not affected.
- Adds a functional test to ensure the slack integration feature is
  not affected by a new commit.

### CODE REVIEW

**Comment by yashashreesuresh** [comment]
Please have a look @chaitanyaenr

**Comment by aakarshg** [comment]
@yashashreesuresh is there a test run/build that gives an idea of how this commit would run with CI?

**Comment by yashashreesuresh** [comment]
> @yashashreesuresh is there a test run/build that gives an idea of how this commit would run with CI?

http://perf-sm5039-4-8.perf.lab.eng.rdu2.redhat.com:8080/job/cerberus_jjb/
Previously I had built it manually on my branch.

**Pull request merged**
